
package formularios;

import dao.DAOProducto;
import javax.swing.JOptionPane;
import modelos.Producto;


public class ProductoCrear extends javax.swing.JInternalFrame {

    /**
     * Creates new form ProductoCrear
     */
    public ProductoCrear() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCabeceraCrearP = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelCuerpoCrearP = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cajaReferencia = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cajaNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cajaPreciocosto = new javax.swing.JTextField();
        cajaPrecioventa = new javax.swing.JTextField();
        panelBotonesCrearP = new javax.swing.JPanel();
        btnCrearProducto = new javax.swing.JButton();
        btnCancelarProducto = new javax.swing.JButton();

        setClosable(true);
        setTitle("PRODUCTOS CREAR");
        setToolTipText("");
        setPreferredSize(new java.awt.Dimension(711, 442));

        panelCabeceraCrearP.setBackground(new java.awt.Color(102, 255, 255));
        panelCabeceraCrearP.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("CREACIÓN   DE   PRODUCTOS");

        javax.swing.GroupLayout panelCabeceraCrearPLayout = new javax.swing.GroupLayout(panelCabeceraCrearP);
        panelCabeceraCrearP.setLayout(panelCabeceraCrearPLayout);
        panelCabeceraCrearPLayout.setHorizontalGroup(
            panelCabeceraCrearPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCabeceraCrearPLayout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(jLabel1)
                .addContainerGap(137, Short.MAX_VALUE))
        );
        panelCabeceraCrearPLayout.setVerticalGroup(
            panelCabeceraCrearPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCabeceraCrearPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelCuerpoCrearP.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Referencia producto: ");

        cajaReferencia.setBackground(new java.awt.Color(255, 255, 153));
        cajaReferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaReferenciaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Nombre producto:");

        cajaNombre.setBackground(new java.awt.Color(255, 204, 255));
        cajaNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaNombreActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Precio de costo:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Precio de venta: ");

        cajaPreciocosto.setBackground(new java.awt.Color(255, 255, 153));
        cajaPreciocosto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaPreciocostoActionPerformed(evt);
            }
        });

        cajaPrecioventa.setBackground(new java.awt.Color(255, 204, 255));
        cajaPrecioventa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaPrecioventaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCuerpoCrearPLayout = new javax.swing.GroupLayout(panelCuerpoCrearP);
        panelCuerpoCrearP.setLayout(panelCuerpoCrearPLayout);
        panelCuerpoCrearPLayout.setHorizontalGroup(
            panelCuerpoCrearPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCuerpoCrearPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCuerpoCrearPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCuerpoCrearPLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cajaReferencia))
                    .addGroup(panelCuerpoCrearPLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cajaNombre))
                    .addGroup(panelCuerpoCrearPLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cajaPreciocosto))
                    .addGroup(panelCuerpoCrearPLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cajaPrecioventa)))
                .addContainerGap())
        );
        panelCuerpoCrearPLayout.setVerticalGroup(
            panelCuerpoCrearPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCuerpoCrearPLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panelCuerpoCrearPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cajaReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(panelCuerpoCrearPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cajaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(23, 23, 23)
                .addGroup(panelCuerpoCrearPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cajaPreciocosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(23, 23, 23)
                .addGroup(panelCuerpoCrearPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cajaPrecioventa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        panelBotonesCrearP.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnCrearProducto.setBackground(new java.awt.Color(0, 204, 0));
        btnCrearProducto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCrearProducto.setText("GUARDAR");
        btnCrearProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearProductoActionPerformed(evt);
            }
        });

        btnCancelarProducto.setBackground(new java.awt.Color(255, 51, 51));
        btnCancelarProducto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCancelarProducto.setText("CANCELAR");
        btnCancelarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarProductoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBotonesCrearPLayout = new javax.swing.GroupLayout(panelBotonesCrearP);
        panelBotonesCrearP.setLayout(panelBotonesCrearPLayout);
        panelBotonesCrearPLayout.setHorizontalGroup(
            panelBotonesCrearPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesCrearPLayout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(btnCrearProducto)
                .addGap(132, 132, 132)
                .addComponent(btnCancelarProducto)
                .addContainerGap(166, Short.MAX_VALUE))
        );
        panelBotonesCrearPLayout.setVerticalGroup(
            panelBotonesCrearPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBotonesCrearPLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelBotonesCrearPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrearProducto)
                    .addComponent(btnCancelarProducto))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelBotonesCrearP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelCuerpoCrearP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelCabeceraCrearP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCabeceraCrearP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelCuerpoCrearP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelBotonesCrearP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarProductoActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarProductoActionPerformed

    private void crearProducto() {
        String cajaReferenciaProducto = cajaReferencia.getText();
        String cajaNombreProducto = cajaNombre.getText();
        Double cajaPreciocostoProducto = Double.parseDouble(cajaPreciocosto.getText());
        Double cajaPrecioventaProducto = Double.parseDouble(cajaPrecioventa.getText());

        if (cajaReferenciaProducto.isEmpty()) {
            JOptionPane.showMessageDialog(panelCuerpoCrearP, "Debe escribir la referencia del producto.");
        } else if (cajaNombreProducto.isEmpty()) {
            JOptionPane.showMessageDialog(panelCuerpoCrearP, "Debe escribir el nombre del producto.");
        } else if (cajaPreciocostoProducto.isNaN()) {
            JOptionPane.showMessageDialog(panelCuerpoCrearP, "Debe escribir el precio de costo del producto.");
        } else if (cajaPrecioventaProducto.isNaN()) {
            JOptionPane.showMessageDialog(panelCuerpoCrearP, "Debe escribir el precio de venta del producto.");
        }
        
        else {
            DAOProducto objDao = new DAOProducto();
            Producto objProducto = new Producto();
            
            objProducto.setReferencia(cajaReferenciaProducto);
            objProducto.setNombre(cajaNombreProducto);
            objProducto.setPrecioCosto(cajaPreciocostoProducto);
            objProducto.setPrecioVenta(cajaPrecioventaProducto);
            
            if(objDao.agregar(objProducto)){
                cajaReferencia.setText("");
                cajaNombre.setText("");
                cajaPreciocosto.setText("");
                cajaPrecioventa.setText("");
                JOptionPane.showMessageDialog(panelCuerpoCrearP, "Registro agregado correctamente.");
            }else{
                JOptionPane.showMessageDialog(panelCuerpoCrearP, "No se puede crear el registro.");
            }
            cajaReferencia.requestFocus();
        }
    }

    private void btnCrearProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearProductoActionPerformed
        crearProducto();
    }//GEN-LAST:event_btnCrearProductoActionPerformed

    private void cajaNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaNombreActionPerformed
        // TODO add your handling code here:
        crearProducto();
    }//GEN-LAST:event_cajaNombreActionPerformed

    private void cajaReferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaReferenciaActionPerformed
        // TODO add your handling code here:
        crearProducto();
    }//GEN-LAST:event_cajaReferenciaActionPerformed

    private void cajaPreciocostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaPreciocostoActionPerformed
        // TODO add your handling code here:
        crearProducto();
    }//GEN-LAST:event_cajaPreciocostoActionPerformed

    private void cajaPrecioventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaPrecioventaActionPerformed
        // TODO add your handling code here:
        crearProducto();
    }//GEN-LAST:event_cajaPrecioventaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarProducto;
    private javax.swing.JButton btnCrearProducto;
    private javax.swing.JTextField cajaNombre;
    private javax.swing.JTextField cajaPreciocosto;
    private javax.swing.JTextField cajaPrecioventa;
    private javax.swing.JTextField cajaReferencia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel panelBotonesCrearP;
    private javax.swing.JPanel panelCabeceraCrearP;
    private javax.swing.JPanel panelCuerpoCrearP;
    // End of variables declaration//GEN-END:variables
}
